language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- gem update --system && gem install compass
- bower install
script:
- grunt build
after_success: curl --ftp-create-dirs -T dist -u $FTP_USER:$FTP_PASSWORD ftp://ftp.tiefenauer.info/web/m3d/