language: node_js
node_js:
- '0.10'
env:
  global:
    secure: CMCKwpeZ/T4mLZRaNCD/ss2Ukcm/GZtn78r7VKFMCAnKZaMkCIP/v4i+S4oPjILUEwIwit9ptFoOtW2ctwWGBhF5p6w5AkcpyGPdtl/ZljzRSpWoY1LK46aukzGXVOqh1vOujglnO5iJZL+EoaDnb8z+6oeeNOglrZZZA8RKeKY=
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g bower grunt-cli
- gem update --system && gem install compass
- bower install
script:
- grunt
after_success:
- chmod +x ./update-gh-pages.sh
- ./update-gh-pages.sh
- cd dist
- find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://ftp.tiefenauer.info/web/m3d/{}
  \;
