language: node_js
node_js:
- '0.10'
env:
  global:
    secure: RpDbeZbKIMQ5pg2MZI7I10dEqeH42ltOkQEVcg7UqvK6wHYp5ZmGwkQf9AIwsIgYpTPB+pT3m4LKD9KI2vT2dZYdONzLJiDGdi+hCAvT+HkdSQZd36VDcLeeQH5v52anllncwRcWz7lmSSQUl+ccZPeObdlRk1tr4IVX6IV0LEM=
before_script:
- npm install -g bower grunt-cli
- gem update --system && gem install compass
- bower install
script:
- grunt build
- grunt test
- grunt coveralls
- npm run metrics
after_success:
- chmod +x ./update-gh-pages.sh
- ./update-gh-pages.sh
- cd dist
- find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://ftp.tiefenauer.info/web/m3d/{}
  \;