language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- gem update --system && gem install compass
- bower install
script:
- grunt build
after_success: curl --ftp-create-dirs -T dist -u $FTP_USER:$FTP_PASSWORD ftp://ftp.tiefenauer.info/web/m3d/
before_install:
- openssl aes-256-cbc -K $encrypted_990172b51f6b_key -iv $encrypted_990172b51f6b_iv
  -in ftp.txt.enc -out ftp.txt -d
