language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- gem update --system && gem install compass
- bower install
script:
- grunt build
- grunt test
- grunt coveralls
- npm run metrics
after_success:
- cd dist
- find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://ftp.tiefenauer.info/web/m3d/{}
  \;
env:
  global:
  - secure: rLNb1EBs1tP8OfcldV8Tvd7/NYoOvBo7+sv7TZlCLgDfxakfEkI/JMxOatN9Ul+FPcyl1gjIUhf4Om1LZUG81VD58tv0fhd/XCe7XPOjHSn/Zku0ffLeq5Tg3bmGm23nuJO7K27Mm4TXn5ICWrUKdPNtpw11MIEQThgQxXqn3jM=
  - secure: byoIfHum2JjqgYgElwNSYyWgrBoPAwr+BVlfSFUacuNJ13FK39YiyW1eIfNAEUKE5u2/hiUMBOdUgXNF/qQSoMSiagQuYjG7NhvccsNxySoInmJERevyhbzFBRunBXr+W/6hILyNBSa6/vErJP+iq0kfhPVvIbN9eumyXmz1DVc=
